### ISSUE TITLE
[Suggestion] Cooperative request

### ISSUE THREAD

**Issue by phoriah** [xAstroBoy/ShowHiddenChannels#10]
I have found another project aiming to fix this big issue.
[here](https://github.com/Saalvage/BetterDiscordAddons)
All I'm saying is if you could potentially team up with them and unite your efforts I think that'd be great.
If more similar projects arise I will try to notify you and them.
Just a suggestion!
Thanks, P.

**Comment by xAstroBoy** [comment]
Sure thing, hit me up in discord and we can talk .
